package com.example.firebase;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.text.TextUtils;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Toast;

import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.auth.AuthResult;
import com.google.firebase.auth.FirebaseAuth;

public class RegisterActivity extends AppCompatActivity {

    // Declare Fields ( view:xml)
    private EditText email ,password ;
    private Button regbtn ;
    private FirebaseAuth auth ;                              //used for firebase authentication

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_register);


         // Linked the fields with xml elements
        email = findViewById(R.id.regemail);
        password = findViewById(R.id.regpassword);
        regbtn = findViewById(R.id.regregister);
        auth = FirebaseAuth.getInstance();


        regbtn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {                                    // when register button clicked
                // fetch the values from view & typecast it to string
                String textemail = email.getText().toString();
                String passwordd = password.getText().toString();



                // Checking credentials empty or not

                if(TextUtils.isEmpty(textemail)|| TextUtils.isEmpty(passwordd)){
                    Toast.makeText(RegisterActivity.this,"Empty creadentials" , Toast.LENGTH_SHORT).show();
                } else if (passwordd.length() < 6 ) {
                    Toast.makeText(RegisterActivity.this, "Password is too short", Toast.LENGTH_SHORT).show();
                } else {
                    // If All things are good the call the method registeruser means create user in firebase
                    registeruser(textemail,passwordd);
                }
            }
        });
    }

    private void registeruser(String emaill, String paswrd) {
        //the method registeruser means create user in firebase
      //  System.out.println("helllooooo"+emaill);   // For detect or cought error the email & password are correct or not
        // System.out.println("helllooooo"+paswrd);

        // THIS LINE IS USED TO CREATE USER via givin email& password and after complete creation  through toast(message prompt) to customer
        auth.createUserWithEmailAndPassword(emaill,paswrd).addOnCompleteListener(RegisterActivity.this, new OnCompleteListener<AuthResult>() {
            @Override
            public void onComplete(@NonNull Task<AuthResult> task) {
         /*     used to Detect error generated by onComplete method
            if (!task.isSuccessful()) {
                    String TAG = "aman";
                    Log.e(TAG, "onComplete: Failed=" + task.getException().getMessage());

                } */
                if(task.isSuccessful()){
                    Toast.makeText(RegisterActivity.this, "successfully registered", Toast.LENGTH_SHORT).show();
                    startActivity(new Intent(RegisterActivity.this ,MainActivity.class));
                    finish();  // when user hit back it finish
                } else {
                    Toast.makeText(RegisterActivity.this, "NOT registered", Toast.LENGTH_SHORT).show();
                }
            }
        });
    }
}